CREATE TABLE STUDENT (	
        "ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(50 BYTE), 
	"AGE" NUMBER NOT NULL ENABLE, 
	"ADDRESS" VARCHAR2(20 BYTE), 
	"STAND" VARCHAR2(20 BYTE), 
	 CONSTRAINT "STUDENT_PK" PRIMARY KEY ("ID")
   ) ;