
  CREATE TABLE ATTACHMENT 
   (	"DOCUMENT_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"DOCUMENT_NAME" VARCHAR2(100 BYTE), 
	"DOCUMENT_SIZE" NUMBER(20,0), 
	"CONTENT_TYPE" VARCHAR2(20 BYTE), 
	"FILE_CONTENT" BLOB, 
	 CONSTRAINT "ATTACHMENT_PK" PRIMARY KEY ("DOCUMENT_ID")
     );
 


  CREATE SEQUENCE  ATTACHMENT_UPLOAD_SEQ  MINVALUE 1 MAXVALUE 99999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;


  CREATE TABLE USER_DETAILS 
   (	"USER_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"USER_NAME" VARCHAR2(20 BYTE), 
	"ROLE" VARCHAR2(20 BYTE),
	CONSTRAINT "USER_DETAILS_PK" PRIMARY KEY ("USER_ID")
   );

